apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: rabbitmq-system
type: Opaque
stringData:
  rabbitmq-user: admin
  rabbitmq-password: changeme123
  rabbitmq-erlang-cookie: RABBITMQ_CLUSTER_COOKIE_VALUE