# Option 1: If your cluster supports dynamic provisioning
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq-storage
  namespace: rabbitmq-system
provisioner: kubernetes.io/gce-pd  # Change this to match your cloud provider
parameters:
  type: pd-standard
  fstype: ext4
---
# Option 2: If you need to create a static PV first
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-0
  labels:
    type: local
spec:
  storageClassName: rabbitmq-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/rabbitmq-0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rabbitmq-0
  namespace: rabbitmq-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: rabbitmq-storage