apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-prometheus-config
  namespace: rabbitmq-system
data:
  rabbitmq-prometheus.conf: |
    prometheus.return_per_object_metrics = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-exporter
  namespace: rabbitmq-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-exporter
  template:
    metadata:
      labels:
        app: rabbitmq-exporter
    spec:
      containers:
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter:v1.0.0-RC11
        env:
        - name: RABBIT_URL
          value: "http://rabbitmq:15672"
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: rabbitmq-user
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: rabbitmq-password
        ports:
        - name: metrics
          containerPort: 9419
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter
  namespace: rabbitmq-system
  labels:
    app: rabbitmq-exporter
spec:
  selector:
    app: rabbitmq-exporter
  ports:
  - name: metrics
    port: 9419
    targetPort: 9419
  type: ClusterIP