apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: bi-system
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    loopback_users.guest = false
    listeners.tcp.default = 5672
    management.tcp.port = 15672