apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
  namespace: bi-system
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: http
    port: 15672
    targetPort: 15672
    nodePort: 30672
  - name: amqp
    port: 5672
    targetPort: 5672
    nodePort: 30673