apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-rabbitmq-config
  namespace: default
data:
  rabbitmq.properties: |
    # Configuración de conexión
    spring.rabbitmq.host=rabbitmq.middleware.svc.cluster.local
    spring.rabbitmq.port=5672
    spring.rabbitmq.username=notification_service
    spring.rabbitmq.password=${RABBITMQ_NOTIFICATION_PASSWORD}
    spring.rabbitmq.virtual-host=/

    # Configuración de intercambios
    rabbitmq.exchange.erp-data=erp.data_changes
    rabbitmq.exchange.ml-score=ml.score_updates
    rabbitmq.exchange.notification=notification.events

    # Colas
    rabbitmq.queue.erp-events=notification.erp_events
    rabbitmq.queue.ml-events=notification.ml_events
    rabbitmq.queue.payment-events=notification.payment_events
    rabbitmq.queue.loan-events=notification.loan_events

    # Dead Letter Queue
    rabbitmq.queue.notification-dlq=notification.dlq